import datetime as dt
import math

LOG_2_PI = math.log(2 * math.pi)
import random

import torch

from matcha.utils import monotonic_align

from matcha import utils
from matcha.models.baselightningmodule import BaseLightningClass
from matcha.models.components.flow_matching import CFM
from matcha.models.components.text_encoder import TextEncoder
from matcha.utils.model import (
    denormalize,
    duration_loss,
    fix_len_compatibility,
    generate_path,
    sequence_mask,
)
from super_monotonic_align import maximum_path

log = utils.get_pylogger(__name__)

class MatchaTTS(BaseLightningClass):  # 🍵
    def __init__(
        self,
        n_vocab,
        n_spks,
        spk_emb_dim,
        n_feats,
        encoder,
        decoder,
        cfm,
        data_statistics,
        optimizer=None, # parameter required by BaseLightningClass
        scheduler=None, # parameter required by BaseLightningClass
        prior_loss=True,
        use_precomputed_durations=False,
        plot_mel_on_validation_end=False,
    ):
        super().__init__()

        self.save_hyperparameters(logger=False)

        self.n_vocab = n_vocab
        self.n_spks = n_spks
        self.spk_emb_dim = spk_emb_dim
        self.n_feats = n_feats
        self.prior_loss = prior_loss
        self.use_precomputed_durations = use_precomputed_durations
        self.plot_mel_on_validation_end = plot_mel_on_validation_end
        self.mas_const = -0.5 * LOG_2_PI * n_feats

        if n_spks > 1:
            self.spk_emb = torch.nn.Embedding(n_spks, spk_emb_dim)

        self.encoder = TextEncoder(
            encoder.encoder_type,
            encoder.encoder_params,
            encoder.duration_predictor_params,
            n_vocab,
            n_spks,
            spk_emb_dim,
        )

        self.decoder = CFM(
            in_channels=2 * encoder.encoder_params.n_feats,
            out_channel=encoder.encoder_params.n_feats,
            cfm_params=cfm,
            decoder_params=decoder,
            n_spks=n_spks,
            spk_emb_dim=spk_emb_dim,
        )

        self.update_data_statistics(data_statistics)

    def mix_speakers(self, speaker_mix):
        """Mix multiple speaker embeddings with given weights.
        
        Args:
            speaker_mix (list): List of (speaker_id, weight) tuples.
                Example: [(2, 0.7), (5, 0.3)] for 70% speaker 2 + 30% speaker 5
        
        Returns:
            torch.Tensor: Mixed speaker embedding, shape: (1, spk_emb_dim)
        """
        if self.n_spks <= 1:
            return None
        
        device = next(self.parameters()).device
        mixed_emb = None
        
        for spk_id, weight in speaker_mix:
            spk_tensor = torch.tensor([spk_id], device=device, dtype=torch.long)
            spk_emb = self.spk_emb(spk_tensor)
            
            if mixed_emb is None:
                mixed_emb = weight * spk_emb
            else:
                mixed_emb += weight * spk_emb
        
        return mixed_emb

    @torch.inference_mode()
    def synthesise(self, x, x_lengths, n_timesteps, temperature=1.0, spks=0, voice_mix=None, length_scale=1.0):
        """
        Generates mel-spectrogram from text. Returns:
            1. encoder outputs
            2. decoder outputs
            3. generated alignment

        Args:
            x (torch.Tensor): batch of texts, converted to a tensor with phoneme embedding ids.
                shape: (batch_size, max_text_length)
            x_lengths (torch.Tensor): lengths of texts in batch.
                shape: (batch_size,)
            n_timesteps (int): number of steps to use for reverse diffusion in decoder.
            temperature (float, optional): controls variance of terminal distribution.
            spks (int, optional): speaker id (default: 0).
            voice_mix (list, optional): List of (speaker_id, weight) tuples for mixing speakers.
                Example: [(2, 0.7), (5, 0.3)] for 70% speaker 2 + 30% speaker 5
                If provided, spks parameter is ignored.
            length_scale (float, optional): controls speech pace.
                Increase value to slow down generated speech and vice versa.

        Returns:
            dict: {
                "encoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Average mel spectrogram generated by the encoder
                "decoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Refined mel spectrogram improved by the CFM
                "attn": torch.Tensor, shape: (batch_size, max_text_length, max_mel_length),
                # Alignment map between text and mel spectrogram
                "mel": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Denormalized mel spectrogram
                "mel_lengths": torch.Tensor, shape: (batch_size,),
                # Lengths of mel spectrograms
                "rtf": float,
                # Real-time factor
            }
        """
        # For RTF computation
        t = dt.datetime.now()

        if self.n_spks > 1:
            if voice_mix is not None:
                spks = self.mix_speakers(voice_mix)
            else:
                device = next(self.parameters()).device
                spks = torch.tensor([spks], device=device, dtype=torch.long)
                spks = self.spk_emb(spks)

        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        mu_x, logw, x_mask = self.encoder(x, x_lengths, spks)

        # Bug fix: removed torch.ceil() that was rounding up each phoneme duration.
        # Rounding up caused systematic bias - speech was consistently too slow.
        # generate_path can handle fractional durations (e.g., 2.37 frames) via cumsum.
        w = torch.exp(logw) * x_mask * length_scale
        y_lengths = torch.clamp_min(torch.sum(w, [1, 2]), 1).round().long()
        y_max_length = y_lengths.max()
        y_max_length_ = fix_len_compatibility(y_max_length)

        # Using obtained durations `w` construct alignment map `attn`
        y_mask = sequence_mask(y_lengths, y_max_length_).unsqueeze(1).to(x_mask.dtype)
        attn_mask = x_mask.unsqueeze(-1) * y_mask.unsqueeze(2)
        attn = generate_path(w.squeeze(1), attn_mask.squeeze(1)).unsqueeze(1)

        # Align encoded text and get mu_y
        mu_y = torch.matmul(attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2))
        mu_y = mu_y.transpose(1, 2)
        encoder_outputs = mu_y[:, :, :y_max_length]

        # Generate sample tracing the probability flow
        decoder_outputs = self.decoder(mu_y, y_mask, n_timesteps, temperature, spks)
        decoder_outputs = decoder_outputs[:, :, :y_max_length]

        t = (dt.datetime.now() - t).total_seconds()
        sr = getattr(self, "sample_rate", 24000)
        hop = getattr(self, "hop_length", 256)
        rtf = t * sr / (decoder_outputs.shape[-1] * hop)

        return {
            "encoder_outputs": encoder_outputs,
            "decoder_outputs": decoder_outputs,
            "attn": attn[:, :, :y_max_length],
            "mel": denormalize(decoder_outputs, self.mel_mean, self.mel_std),
            "mel_lengths": y_lengths,
            "rtf": rtf,
        }

    def forward(self, x, x_lengths, y, y_lengths, spks=None, cond=None, durations=None):
        """
        Computes 3 losses:
            1. duration loss: loss between predicted token durations and those extracted by Monotonic Alignment Search (MAS).
            2. prior loss: loss between mel-spectrogram and encoder outputs.
            3. flow matching loss: loss between mel-spectrogram and decoder outputs.

        Args:
            x (torch.Tensor): batch of texts, converted to a tensor with phoneme embedding ids.
                shape: (batch_size, max_text_length)
            x_lengths (torch.Tensor): lengths of texts in batch.
                shape: (batch_size,)
            y (torch.Tensor): batch of corresponding mel-spectrograms.
                shape: (batch_size, n_feats, max_mel_length)
            y_lengths (torch.Tensor): lengths of mel-spectrograms in batch.
                shape: (batch_size,)
            spks (torch.Tensor, optional): speaker ids.
                shape: (batch_size,)
        """
        if self.n_spks > 1:
            # Get speaker embedding
            spks = self.spk_emb(spks)

        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        mu_x, logw, x_mask = self.encoder(x, x_lengths, spks)
        y_max_length = y.shape[-1]

        y_mask = sequence_mask(y_lengths, y_max_length).unsqueeze(1).to(x_mask)
        attn_mask = x_mask.unsqueeze(-1) * y_mask.unsqueeze(2)

        if self.use_precomputed_durations:
            attn = generate_path(durations.squeeze(1), attn_mask.squeeze(1))
        else:
            # Use MAS to find most likely alignment `attn` between text and mel-spectrogram
            with torch.no_grad():
                factor = -0.5 * torch.ones(mu_x.shape, dtype=mu_x.dtype, device=mu_x.device)
                y_square = torch.matmul(factor.transpose(1, 2), y**2)
                # Original code was:
                #   y_mu_double = torch.matmul(2.0 * (factor * mu_x).transpose(1, 2), y)
                # But (2.0 * factor * mu_x) is useless, because factor = -0.5 * tensor.ones
                # I've replaced it with just -mu_x
                y_mu_double = torch.matmul(-mu_x.transpose(1, 2), y)
                mu_square = torch.sum(factor * (mu_x**2), 1).unsqueeze(-1)
                log_prior = y_square - y_mu_double + mu_square + self.mas_const

                # the GPU impl is about 5% faster, but triggers more model recompilations.
                attn = maximum_path(log_prior, attn_mask.squeeze(1).to(torch.int32), log_prior.dtype)
                # attn = monotonic_align.maximum_path_cpu(log_prior, attn_mask.squeeze(1))

        # torch.sum(attn.unsqueeze(1), -1)) says how many mel frames each text token aligns to
        # x_mask has 1s for valid text tokens, 0s for padding positions, to ensure loss is only calculated on 
        # valid tokens, preventing attention to padding.
        logw_ = torch.log(1e-8 + torch.sum(attn.unsqueeze(1), -1)) * x_mask
        # logw - log-scaled durations calculated by the TextEncoder's duration predictor
        # logw_ - log-scaled durations calculated the Monotonic Alignment Search algorithm. 
        dur_loss = duration_loss(logw, logw_, x_lengths)

        # Align encoded text with mel-spectrogram and get mu_y segment
        # Original code was:
        #   mu_y = torch.matmul(attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2))
        #   mu_y = mu_y.transpose(1, 2)
        # but that can be simplified as: 
        mu_y = torch.matmul(mu_x, attn.squeeze(1))

        # Compute loss of the decoder
        diff_loss, _ = self.decoder.compute_loss(x1=y, mask=y_mask, mu=mu_y, spks=spks, cond=cond)

        if self.prior_loss:
            # Original code was: 
            #   prior_loss = torch.sum(0.5 * ((y - mu_y) ** 2 + math.log(2 * math.pi)) * y_mask)
            # but that is just wasted computation.
            # I could remove the constants without affecting the meaning of the loss.
            # prior_loss = torch.sum(((y - mu_y) ** 2) * y_mask)
            prior_loss = torch.sum(0.5 * ((y - mu_y) ** 2 + LOG_2_PI) * y_mask)
            prior_loss = prior_loss / (torch.sum(y_mask) * self.n_feats)
        else:
            prior_loss = 0

        # Gradient scaling: keeps prior_loss value unchanged for logging, 
        # but amplifies its gradient, because it is to0 small, 
        # I can probably achieve the same thing with:
        #   def configure_optimizers(self):
        #       optimizer = torch.optim.AdamW([
        #           {'params': self.text_encoder.parameters(), 'lr': self.hparams.encoder_lr},
        #           {'params': self.decoder.parameters(), 'lr': self.hparams.decoder_lr},
        #           {'params': self.duration_predictor.parameters(), 'lr': self.hparams.duration_lr}
        #       ])
        #       return optimizer
        # but this is simpler:  
        #   scaled_loss = prior_loss * 30 - prior_loss.detach() * 29
        scaled_loss = prior_loss * 100 - prior_loss.detach() * 99
        return diff_loss, dur_loss, scaled_loss
