# Changed from [256, 256]
# I must have attention_head_dim * num_heads == channels so the attention will cover all channels.
#
# If you change the number of channels here, update the num_downsamplings_in_unet in fix_len_compatibility().
# At the moment, the code assumes there are 2 values in this array (the model will do 1 down-sampling).
# Num channels must be at least as big as 2 * n_feats + spk_emb_dim. 
# n_feats is 100, imposed by vocos and spk_emb_dim is set to 96 in matchat.yaml => 296
channels: [320, 320]

# This model does not show a lot of overfitting, so I can use the original value of 0.05.
dropout: 0.05

# It used to be recommended that num channels / num heads should be at least 64 
attention_head_dim: 64

# Increased from 1, to capture more acoustic details.
# This makes training and inference slower.
n_blocks: 2

num_mid_blocks: 2

# Changed from 2
num_heads: 5