import math
from abc import ABC

import torch
import torch.nn.functional as F
from torchdiffeq import odeint

from matcha.models.components.decoder import Decoder
from .ode_solver_wrapper import OdeSolverWrapper

# Controls the distribution of training timesteps along the noise-to-mel trajectory, so the model spends 
# more time training in the middle of the trajectory.
# The velocity target is hardest to predict in the middle of the trajectory, because near either end
# the best possible prediction is simply the mean of the noise or the mean of the target mels.
# This  logit-normal density, was described by Esser et al. 2024 in "Scaling Rectified Flow Transformers".
# They found to be the best of 61 formulations, both overall and when sampling with as few steps as I use in inference.
# Location 0.0 keeps the density symmetric around the middle, so the direction in which the
# trajectory runs does not matter. Negative values move sampling towards the start, positive values towards destination.
TIMESTEP_SAMPLING_LOCATION = -0.6
# Larger scale widens the density towards both ends, and a smaller scale # concentrates it more tightly in the middle. 
# Scale: 1.0 middle focused, 1.4 wider hump, 1.8 as uniform as it gets with this formula.
TIMESTEP_SAMPLING_SCALE = 1.2

# Controls the location of inference timesteps, so the solver takes short steps near the beginning of the
# trajectory and longer ones near the destination. This was described in "Sway Sampling", by Chen et al. 2024, F5-TTS.
# The coarse structure of the speech is formed during the early steps, so giving the solver more
# resolution there was reported to improve quality at a low number of steps, at no extra cost.
# 0.0 produces an evenly spaced grid. Negative values move steps towards the noise end,
# positive values towards the mel end. The mapping stays monotonic between -1.0 and 2 / (pi - 2).
SWAY_SAMPLING_COEFFICIENT = -1.0

class BASECFM(torch.nn.Module, ABC):
    def __init__(
        self,
        n_feats,
        cfm_params,
    ):
        super().__init__()
        self.n_feats = n_feats
        self.solver = cfm_params.solver
        self.sigma_min = getattr(cfm_params, "sigma_min", 1e-4)
        self.use_mu_prior = getattr(cfm_params, "use_mu_prior", False)

        self.estimator = None

    @torch.inference_mode()
    def forward(self, mu, mask, n_timesteps):
        """Forward diffusion

        Args:
            mu (torch.Tensor): the mel-spectrogram generated by the encoder
                shape: (batch_size, n_feats, mel_timesteps)
            mask (torch.Tensor): Binary mask indicating valid mel frames (1) vs padding (0).
                shape: (batch_size, 1, mel_timesteps)
            n_timesteps (int): number of diffusion steps
        Returns:
            sample: generated mel-spectrogram
                shape: (batch_size, n_feats, mel_timesteps)
        """


        # Set seed for reproducible synthesis; without this, the voice sounds slightly different 
        #  with each synthesis call so MCD metrics are not reliable.
        generator = torch.Generator(device=mu.device)
        generator.manual_seed(42)
        
        # The MathaTTS white paper recommends to start from mu (the encoder's mel prediction) + noise.
        # The decoder would then only need to refine it.
        # Still, the original Matcha-TTS GIT code was not adding mu, and ODE was starting from pure noise.
        # The author addressed this in GitHub Issue #141, arguing that mu is concatenated to the input of the UNet/Decoder. 
        # Because the model "sees" mu at every step, the author found that it can learn to find the data just as well starting from.
        # He noted that in practice, they didn't see much difference in quality when switching between the two. 
        if self.use_mu_prior:
            z = mu + torch.randn_like(mu, generator=generator)
        else:
            z = torch.randn_like(mu, generator=generator)
        
        t_span = self.build_step_grid(n_timesteps, mu.device)
        return self.solve(z, t_span=t_span, mu=mu, mask=mask)

    def build_step_grid(self, n_timesteps, device):
        """Builds the sequence of trajectory positions that delimit the ODE solver's steps.

        Both ends are always 0 and 1; only the spacing in between changes.
        See SWAY_SAMPLING_COEFFICIENT for what the spacing does and why.

        Args:
            n_timesteps (int): number of solver steps, so the grid holds n_timesteps + 1 positions
            device (torch.device): device the grid is built on
        Returns:
            step_grid: increasing positions from 0 to 1
                shape: (n_timesteps + 1,)
        """
        evenly_spaced_grid = torch.linspace(0, 1, n_timesteps + 1, device=device)
        if SWAY_SAMPLING_COEFFICIENT == 0.0:
            return evenly_spaced_grid

        sway_offset = torch.cos(0.5 * math.pi * evenly_spaced_grid) - 1.0 + evenly_spaced_grid
        return evenly_spaced_grid + SWAY_SAMPLING_COEFFICIENT * sway_offset

    def solve(self, x, t_span, mu, mask):
        ode_func = OdeSolverWrapper(self.estimator, mask, mu)
        trajectory = odeint(ode_func, x, t_span, method=self.solver)
        return trajectory[-1]

    def compute_loss(self, x1, mask, mu):
        """Computes diffusion loss

        Args:
            x1 (torch.Tensor): Target mel-spectrogram (ground truth from training data).
                shape: (batch_size, n_feats, mel_timesteps)
            mask (torch.Tensor): Binary mask indicating valid mel frames (1) vs padding (0).
                shape: (batch_size, 1, mel_timesteps)
            mu (torch.Tensor): Encoder output - the mel-spectrogram generated by the encoder
                This serves as the conditioning signal for the flow matching process.
                shape: (batch_size, n_feats, mel_timesteps)
        Returns:
            loss: conditional flow matching loss (L1 distance between predicted and target flow)
            y: conditional flow - interpolated sample between noise and target at time t
                shape: (batch_size, n_feats, mel_timesteps)
        """
        b = mu.shape[0]

        # Random timestep, concentrated in the middle of the trajectory (see the constants on top)
        normal_sample = torch.randn([b, 1, 1], device=mu.device, dtype=mu.dtype)
        t = torch.sigmoid(normal_sample * TIMESTEP_SAMPLING_SCALE + TIMESTEP_SAMPLING_LOCATION)
        # Start from mu + noise or pure noise depending on use_mu_prior (see cfm yaml), must match inference.
        if self.use_mu_prior:
            x0 = mu + torch.randn_like(x1)
        else:
            x0 = torch.randn_like(x1)

        # "y" is an interpolated sample between prior and the target spectrogram at timestep t.
        # It represents what the mel-spectrogram looks like at time t during the diffusion process.
        y = (1 - (1 - self.sigma_min) * t) * x0 + t * x1
        # "u" is the target velocity - the optimal direction to flow from prior to target.
        u = x1 - (1 - self.sigma_min) * x0
        
        pred = self.estimator(y, mask, mu, t.squeeze())

        # I think the original loss calculation included padding, and the value from padding was huge.
        # Loss with padding: 1.355872
        # Loss properly masked: 0.052236
        # original_loss = F.mse_loss(pred, u, reduction="sum") / (torch.sum(mask) * u.shape[1])
        # Applying the mask to both the prediction and the target, ensures the loss is based only
        # on the actual speech frames and the padding does not contribute to the loss:
        loss = F.mse_loss(pred * mask, u * mask, reduction="sum") / (torch.sum(mask) * u.shape[1])
        
        return loss


class CFM(BASECFM):
    def __init__(self, in_channels, out_channel, cfm_params, decoder_params):
        super().__init__(
            n_feats=in_channels,
            cfm_params=cfm_params,
        )

        self.estimator = Decoder(in_channels=in_channels, out_channels=out_channel, **decoder_params)
