import io
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
from matcha.models.components.flow_matching import CFM
from matcha.models.components.text_encoder import TextEncoder
from matcha.utils.model import denormalize, fix_len_compatibility, generate_path, sequence_mask
from matcha.text.phonemizers import multilingual_phonemizer, phone_id_to_display
from matcha.text.symbols import N_VOCAB
from matcha.vocos24k.vocos_wrapper import load_model as load_vocos
import av
import numpy as np
from matcha.utils.mp3_converter import encode_mp3

SAMPLE_RATE = 24000

VOICES = [
    {"id":  "0", "lang": "en-us", "gender": "male",   "name": "Kai",    "scale_correction":  0.12},
    {"id":  "1", "lang": "en-us", "gender": "female", "name": "Jane",   "scale_correction":  0.05},
    {"id":  "2", "lang": "en-us", "gender": "female", "name": "Aria",   "scale_correction":  0.05},
    {"id":  "3", "lang": "en-us", "gender": "female", "name": "Bella",  "scale_correction":  0.00},
    {"id":  "4", "lang": "en-gb", "gender": "male",   "name": "Brian",  "scale_correction":  0.09},
    {"id":  "5", "lang": "en-gb", "gender": "male",   "name": "Arthur", "scale_correction":  0.06},
    {"id":  "6", "lang": "en-us", "gender": "female", "name": "Nicole", "scale_correction":  0.02},
    {"id":  "7", "lang": "ro",    "gender": "male",   "name": "Emil",   "scale_correction":  0.07},
    {"id":  "8", "lang": "fr-fr", "gender": "female", "name": "Denise", "scale_correction":  0.04},
    {"id":  "9", "lang": "fr-fr", "gender": "male",   "name": "Henri",  "scale_correction":  0.02},
    {"id": "10", "lang": "ro",    "gender": "female", "name": "Daria",  "scale_correction":  0 },
]

HOP_LENGTH = 256
ODE_SOLVER = "midpoint"
DEVICE = torch.device("cuda")

class MatchaTTSInfer(nn.Module):
    def __init__(self, n_spks, n_feats, encoder, decoder, cfm, data_statistics, spk_emb_dim, **_):
        super().__init__()
        self.speaker_embeddings = nn.Embedding(n_spks, spk_emb_dim)
        n_vocab = N_VOCAB
        self.encoder = TextEncoder(encoder.encoder_params,
                                   encoder.duration_predictor_params, n_vocab, spk_emb_dim)
        self.decoder = CFM(in_channels=2 * n_feats, out_channel=n_feats, cfm_params=cfm, decoder_params=decoder)
        stats = data_statistics or {}
        self.register_buffer("mel_mean", torch.tensor(stats.get("mel_mean", 0.0)))
        self.register_buffer("mel_std", torch.tensor(stats.get("mel_std", 1.0)))

    def mix_speakers(self, speaker_mix):
        """
        Mix multiple speaker embeddings with given weights.

        Args:
            speaker_mix (list): List of (speaker_id, weight) tuples.
        Example:
            [(2, 0.7), (5, 0.3)] for 70% speaker 2 + 30% speaker 5
        Returns:
            speaker embeddings, shape (1, spk_emb_dim)
        """
        device = next(self.parameters()).device
        mixed = None
        for spk_id, weight in speaker_mix:
            spk_tensor = torch.tensor([spk_id], device=device, dtype=torch.long)
            e = self.speaker_embeddings(spk_tensor)
            mixed = weight * e if mixed is None else mixed + weight * e
        return mixed

    def synthesise(self, x, x_lengths, n_timesteps, speaker=0, voice_mix=None, scale_correction=0, length_scale=1.0, debug=False):
        """
        Generates mel-spectrogram from text. Returns:
            1. encoder outputs
            2. decoder outputs
            3. generated alignment

        Args:
            x (torch.Tensor): batch of texts, converted to a tensor with phoneme embedding ids.
                shape: (batch_size, max_text_length)
            x_lengths (torch.Tensor): lengths of texts in batch.
                shape: (batch_size,)
            n_timesteps (int): number of steps to use for reverse diffusion in decoder.
            speaker (int, optional): speaker id (default: 0).
            voice_mix (list, optional): List of (speaker_id, weight) tuples for mixing speakers.
                Example: [(2, 0.7), (5, 0.3)] for 70% speaker 2 + 30% speaker 5
                If provided, speaker parameter is ignored.
            length_scale (float, optional): controls speech pace.
                Increase value to slow down generated speech and vice versa.

        Returns:
            dict: {
                "encoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Average mel spectrogram generated by the encoder
                "decoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Refined mel spectrogram improved by the CFM
                "attn": torch.Tensor, shape: (batch_size, max_text_length, max_mel_length),
                # Alignment map between text and mel spectrogram
                "mel": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Denormalized mel spectrogram
                "mel_lengths": torch.Tensor, shape: (batch_size,),
                # Lengths of mel spectrograms
                "rtf": float,
                # Real-time factor
            }
        """

        if voice_mix is not None:
            speaker_embedding = self.mix_speakers(voice_mix)
        else:
            device = next(self.parameters()).device
            spk_tensor = torch.tensor([speaker], device=device, dtype=torch.long)
            speaker_embedding = self.speaker_embeddings(spk_tensor)

        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        mu_x, logw, x_mask = self.encoder(x, x_lengths, speaker_embedding)

        # I am doing -2 to compensate for the +2 added during training, see matcha_tts
        phoneme_durations = (torch.exp(logw) - 2) * x_mask
        phoneme_durations = phoneme_durations.squeeze(1)
        raw_phoneme_durations = phoneme_durations.clone()

        # scale_correction is the per-speaker correction factor measured after training, by comparing
        # generated speech to ground truth. A scale of 1.08 means the model underestimates total duration by 8%.
        # I believe the model underestimates each phoneme duration by a small number of frames. I believe the errors are
        # not proportional to the phoneme length. If so, it means, short phonemes are affected more.
        # I decided to apply an additive correction, instead of a multiplicative one.
        # We spread the missing frames equally across all phonemes so short phonemes benefit more than long ones.
        predicted_total_frames = phoneme_durations.sum(dim=1, keepdim=True)
        n_phonemes = x_lengths.unsqueeze(1).float()
        correction = predicted_total_frames * scale_correction / n_phonemes
        phoneme_durations = phoneme_durations + correction

        phoneme_durations = phoneme_durations * length_scale

        # Original code was:
        #  w = torch.exp(logw) * x_mask
        #  w_ceil = torch.ceil(w) * length_scale
        #  y_lengths = torch.clamp_min(torch.sum(w_ceil, [1, 2]), 1).long()
        # Rounding up (ceil) each phoneme duration was causing the generated speech to be consistently too slow.
        # Now we round each phoneme duration to the nearest integer and we clamp to minimum 1 to avoid silent phonemes.
        # E.g. durations [3.66, 1.17, 0.49] -> [4, 1, 1]
        phoneme_durations = phoneme_durations.round() * x_mask.squeeze(1)

        # Ensure fine length is compatible with the UNet and even number
        y_fine_lengths = torch.clamp_min(phoneme_durations.sum(dim=1).long(), 1)
        y_fine_max_length = y_fine_lengths.max()
        y_fine_max_length_ = fix_len_compatibility(y_fine_max_length) * 2

        y_fine_mask = sequence_mask(y_fine_lengths, y_fine_max_length_).unsqueeze(1).to(x_mask.dtype)
        attn_mask_fine = x_mask.unsqueeze(-1) * y_fine_mask.unsqueeze(2)
        attn_fine = generate_path(phoneme_durations, attn_mask_fine.squeeze(1)).unsqueeze(1)

        # Matmul in bf16 causes some precision problems in training, so I thought I would use fp32 here too
        with torch.autocast(device_type="cuda", enabled=False):
            # Original code was 
            # mu_y = torch.matmul(attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2))
            # mu_y = mu_y.transpose(1, 2)
            # but that can be simplified as:
            mu_y_fine = torch.matmul(mu_x.float(), attn_fine.float().squeeze(1))

        # Downsample fine resolution predicted mel to standard resolution for the decoder
        mu_y = F.avg_pool1d(mu_y_fine, kernel_size=2, stride=2)
        y_max_length_ = y_fine_max_length_ // 2
        y_lengths = torch.clamp_min((y_fine_lengths + 1) // 2, 1)
        y_max_length = y_lengths.max()
        y_mask = sequence_mask(y_lengths, y_max_length_).unsqueeze(1).to(x_mask.dtype)

        decoder_outputs = self.decoder(mu_y, y_mask, n_timesteps)
        decoder_outputs = decoder_outputs[:, :, :y_max_length]

        mel = denormalize(decoder_outputs, self.mel_mean, self.mel_std)
        if debug:
            return {
                "mel": mel,
                "encoder_mel": denormalize(mu_y[:, :, :y_max_length], self.mel_mean, self.mel_std),
                "phoneme_durations": phoneme_durations,
                "raw_phoneme_durations": raw_phoneme_durations,
            }
        else:
            return { "mel":  mel }


def load_matcha(model_name, checkpoint_path):
    print(f"[!] Loading {model_name}!")
    ckpt = torch.load(checkpoint_path, map_location=DEVICE, weights_only=False)
    hparams = ckpt["hyper_parameters"]
    hparams.pop("optimizer", None)
    hparams.pop("scheduler", None)
    sd = ckpt["state_dict"]
    model = MatchaTTSInfer(**hparams).to(DEVICE)
    model.load_state_dict(sd, strict=False)
    model.eval()
    print(f"[+] {model_name} loaded!")
    return model


def process_text(text: str, language: str):
    separated_phonemes, phoneme_ids = multilingual_phonemizer(text, language)
    phonemes = "".join(separated_phonemes)
    x = torch.tensor(phoneme_ids, dtype=torch.long, device=DEVICE)[None]
    x_lengths = torch.tensor([x.shape[-1]], dtype=torch.long, device=DEVICE)
    print(f"Input text:      <{text}>")
    print(f"Phonetised text: <{phonemes}>")
    return {"x_orig": text, "x": x, "x_lengths": x_lengths, "x_phones": phonemes, "x_phone_ids": phoneme_ids}


def load_vocoder(vocoder_name):
    print(f"[!] Loading {vocoder_name}!")
    if vocoder_name == "vocos":
        vocoder = load_vocos(DEVICE)
    else:
        raise NotImplementedError(f"Vocoder {vocoder_name} not implemented!")
    print(f"[+] {vocoder_name} loaded!")
    return vocoder


@torch.inference_mode()
def pipeline(model, vocoder, text, language, speaker=0, voice_mix=None, n_timesteps=15, scale_correction=0, length_scale=1.0, debug=False):
    text_processed = process_text(text, language)
    with torch.autocast(device_type="cuda"):
        output = model.synthesise(
            text_processed["x"],
            text_processed["x_lengths"],
            n_timesteps=n_timesteps,
            speaker=speaker,
            voice_mix=voice_mix,
            scale_correction=scale_correction,
            length_scale=length_scale,
            debug=debug,
        )
    if not debug:
        return trim_trailing_silence(to_waveform(output["mel"], vocoder))
    x_phones = [phone_id_to_display(id) for id in text_processed["x_phone_ids"]]
    all_durations = output["phoneme_durations"].squeeze(0).tolist()
    all_raw_durations = output["raw_phoneme_durations"].squeeze(0).tolist()
    phoneme_dur_pairs = list(zip(x_phones, all_raw_durations, all_durations))
    waveform = trim_trailing_silence(to_waveform(output["mel"], vocoder))
    encoder_waveform = to_waveform(output["encoder_mel"], vocoder)
    return waveform, encoder_waveform, phoneme_dur_pairs


def to_waveform(mel, vocoder):
    audio = vocoder(mel)
    max_abs = audio.abs().max()
    if max_abs > 1.0:
        audio = audio / max_abs * 0.95
    return audio.cpu().squeeze()


def trim_trailing_silence(audio, silence_threshold_db=-60.0):
    """Trim trailing silence from a 1-D waveform tensor using 10ms RMS windows."""
    window_frames = int(0.01 * SAMPLE_RATE)
    silence_threshold_amp = 10 ** (silence_threshold_db / 20.0)

    n_full_windows = len(audio) // window_frames
    windowed = audio[:n_full_windows * window_frames].reshape(n_full_windows, window_frames)
    rms = windowed.pow(2).mean(dim=1).sqrt()

    trailing_silent_windows = 0
    for i in range(len(rms) - 1, -1, -1):
        if rms[i] < silence_threshold_amp:
            trailing_silent_windows += 1
        else:
            break

    trim_samples = trailing_silent_windows * window_frames
    if trim_samples == 0:
        return audio
    return audio[:-trim_samples]


def convert_to_mp3(waveform):
    start = time.perf_counter()
    audio_np = (waveform.numpy() * 32767).astype(np.int16)
    wav_size = audio_np.size * 2
    mp3_data = encode_mp3(audio_np, sample_rate=SAMPLE_RATE, vbr_quality=5, algorithm_quality=5)
    pct = (len(mp3_data) / wav_size * 100) if wav_size > 0 else 0
    print(f"MP3 conversion: {(time.perf_counter() - start)*1000:.1f}ms | {pct:.0f}% size")
    return mp3_data


def convert_to_opus_ogg(waveform):
    start = time.perf_counter()
    audio_np = (waveform.numpy() * 32767).astype(np.int16).reshape(1, -1)
    wav_size = audio_np.size * 2
    buffer = io.BytesIO()
    container = av.open(buffer, mode='w', format='ogg')
    stream = container.add_stream('libopus', rate=SAMPLE_RATE)
    stream.layout = 'mono'
    stream.bit_rate = 48000
    stream.options = {'compression_level': "5"}
    frame = av.AudioFrame.from_ndarray(audio_np, format='s16', layout='mono')
    frame.sample_rate = SAMPLE_RATE
    for packet in stream.encode(frame):
        container.mux(packet)
    for packet in stream.encode():
        container.mux(packet)
    container.close()
    ogg_data = buffer.getvalue()
    pct = (len(ogg_data) / wav_size * 100) if wav_size > 0 else 0
    print(f"OGG conversion: {(time.perf_counter() - start)*1000:.1f}ms | {pct:.0f}% size")
    return bytes(ogg_data)


