import io
import time
import torch
import torch.nn as nn
import torch.nn.functional as functional
from matcha.models.components.flow_matching import CFM
from matcha.models.components.text_encoder import TextEncoder
from matcha.utils.model import denormalize, fix_len_compatibility, generate_path, sequence_mask
from matcha.text.phonemizers import multilingual_phonemizer
from matcha.text.symbols import symbols
from matcha.vocos24k.vocos_wrapper import load_model as load_vocos
import av
import numpy as np
from matcha.utils.mp3_converter import encode_mp3

SAMPLE_RATE = 24000

VOICES = [
    {"id":  "0", "lang": "en-us", "gender": "male",   "name": "Kai",    "default_scale": 1.0},
    {"id":  "1", "lang": "en-us", "gender": "female", "name": "Jane",   "default_scale": 1.0},
    {"id":  "2", "lang": "en-us", "gender": "female", "name": "Aria",   "default_scale": 1.0},
    {"id":  "3", "lang": "en-gb", "gender": "female", "name": "Bella",  "default_scale": 1.0},
    {"id":  "4", "lang": "en-gb", "gender": "male",   "name": "Brian",  "default_scale": 1.0},
    {"id":  "5", "lang": "en-gb", "gender": "male",   "name": "Arthur", "default_scale": 1.0},
    {"id":  "6", "lang": "en-us", "gender": "female", "name": "Nicole", "default_scale": 0.9},
    {"id":  "7", "lang": "ro",    "gender": "male",   "name": "Emil",   "default_scale": 1.0},
    {"id":  "8", "lang": "fr-fr", "gender": "female", "name": "Denise", "default_scale": 1.0},
    {"id":  "9", "lang": "fr-fr", "gender": "male",   "name": "Henri",  "default_scale": 1.0},
    {"id": "10", "lang": "ro",    "gender": "female", "name": "Daria",  "default_scale": 1},
]

HOP_LENGTH = 256
ODE_SOLVER = "midpoint"
DEVICE = torch.device("cuda")

class MatchaTTSInfer(nn.Module):
    def __init__(self, n_spks, n_feats, encoder, decoder, cfm, data_statistics, spk_emb_dim, **_):
        super().__init__()
        self.speaker_embeddings = nn.Embedding(n_spks, spk_emb_dim)
        n_vocab = len(symbols)
        self.encoder = TextEncoder(encoder.encoder_params,
                                   encoder.duration_predictor_params, n_vocab, spk_emb_dim)
        self.decoder = CFM(in_channels=2 * n_feats, out_channel=n_feats, cfm_params=cfm, decoder_params=decoder)
        stats = data_statistics or {}
        self.register_buffer("mel_mean", torch.tensor(stats.get("mel_mean", 0.0)))
        self.register_buffer("mel_std", torch.tensor(stats.get("mel_std", 1.0)))

    def mix_speakers(self, speaker_mix):
        """
        Mix multiple speaker embeddings with given weights.

        Args:
            speaker_mix (list): List of (speaker_id, weight) tuples.
        Example:
            [(2, 0.7), (5, 0.3)] for 70% speaker 2 + 30% speaker 5
        Returns:
            speaker embeddings, shape (1, spk_emb_dim)
        """
        device = next(self.parameters()).device
        mixed = None
        for spk_id, weight in speaker_mix:
            spk_tensor = torch.tensor([spk_id], device=device, dtype=torch.long)
            e = self.speaker_embeddings(spk_tensor)
            mixed = weight * e if mixed is None else mixed + weight * e
        return mixed

    def synthesise(self, x, x_lengths, n_timesteps, speaker=0, voice_mix=None, length_scale=1.0, debug=False):
        """
        Generates mel-spectrogram from text. Returns:
            1. encoder outputs
            2. decoder outputs
            3. generated alignment

        Args:
            x (torch.Tensor): batch of texts, converted to a tensor with phoneme embedding ids.
                shape: (batch_size, max_text_length)
            x_lengths (torch.Tensor): lengths of texts in batch.
                shape: (batch_size,)
            n_timesteps (int): number of steps to use for reverse diffusion in decoder.
            speaker (int, optional): speaker id (default: 0).
            voice_mix (list, optional): List of (speaker_id, weight) tuples for mixing speakers.
                Example: [(2, 0.7), (5, 0.3)] for 70% speaker 2 + 30% speaker 5
                If provided, speaker parameter is ignored.
            length_scale (float, optional): controls speech pace.
                Increase value to slow down generated speech and vice versa.

        Returns:
            dict: {
                "encoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Average mel spectrogram generated by the encoder
                "decoder_outputs": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Refined mel spectrogram improved by the CFM
                "attn": torch.Tensor, shape: (batch_size, max_text_length, max_mel_length),
                # Alignment map between text and mel spectrogram
                "mel": torch.Tensor, shape: (batch_size, n_feats, max_mel_length),
                # Denormalized mel spectrogram
                "mel_lengths": torch.Tensor, shape: (batch_size,),
                # Lengths of mel spectrograms
                "rtf": float,
                # Real-time factor
            }
        """

        if voice_mix is not None:
            speaker_embedding = self.mix_speakers(voice_mix)
        else:
            device = next(self.parameters()).device
            spk_tensor = torch.tensor([speaker], device=device, dtype=torch.long)
            speaker_embedding = self.speaker_embeddings(spk_tensor)

        # Get encoder_outputs `mu_x` and log-scaled token durations `logw`
        mu_x, logw, x_mask = self.encoder(x, x_lengths, speaker_embedding)

        # Original code was:
        #  w = torch.exp(logw) * x_mask
        #  w_ceil = torch.ceil(w) * length_scale
        #  y_lengths = torch.clamp_min(torch.sum(w_ceil, [1, 2]), 1).long()
        # Rounding up each phoneme duration, was causing the generated speech to be consistently too slow.
        # But generate_path can handle fractional durations so I can pass w as is.
        phoneme_durations = torch.exp(logw) * x_mask * length_scale
        raw_phoneme_durations = phoneme_durations.clone()

        # Round phoneme positions to avoid collisions (2 phonemes starting on the same position).
        # E.g. durations [1.5, 0.5, 1.5] -> cumsum [1.5, 2.0, 3.5] -> round [2, 2, 4].
        # Enforce strictly monotonic integer positions, then derive integer durations from them.
        phoneme_positions = torch.cumsum(phoneme_durations.squeeze(1), 1).round()
        num_phonemes = phoneme_positions.size(1) + 1
        indices = torch.arange(1, num_phonemes, device=phoneme_durations.device)
        phoneme_positions = torch.maximum(phoneme_positions, indices.unsqueeze(0))
        phoneme_durations = phoneme_positions - functional.pad(phoneme_positions, (1, 0))[:, :-1]
        
        y_lengths = torch.clamp_min(phoneme_positions[:, -1].long(), 1)
        y_max_length = y_lengths.max()
        y_max_length_ = fix_len_compatibility(y_max_length)

        # Using obtained durations `w` construct alignment map `attn`
        y_mask = sequence_mask(y_lengths, y_max_length_).unsqueeze(1).to(x_mask.dtype)
        attn_mask = x_mask.unsqueeze(-1) * y_mask.unsqueeze(2)
        attn = generate_path(phoneme_durations, attn_mask.squeeze(1)).unsqueeze(1)

        # Align encoded text and get mu_y
        # Original code was 
        # mu_y = torch.matmul(attn.squeeze(1).transpose(1, 2), mu_x.transpose(1, 2))
        # mu_y = mu_y.transpose(1, 2)
        # but that can be simplified as:
        mu_y = torch.matmul(mu_x, attn.squeeze(1))

        # Generate speech tracing the probability flow
        decoder_outputs = self.decoder(mu_y, y_mask, n_timesteps)
        decoder_outputs = decoder_outputs[:, :, :y_max_length]

        mel = denormalize(decoder_outputs, self.mel_mean, self.mel_std)
        if debug:
            return {
                "mel": mel,
                "encoder_mel": denormalize(mu_y[:, :, :y_max_length], self.mel_mean, self.mel_std),
                "phoneme_durations": phoneme_durations.squeeze(1),
                "raw_phoneme_durations": raw_phoneme_durations.squeeze(1),
            }
        else:
            return { "mel":  mel }


def load_matcha(model_name, checkpoint_path):
    print(f"[!] Loading {model_name}!")
    ckpt = torch.load(checkpoint_path, map_location=DEVICE, weights_only=False)
    hparams = ckpt["hyper_parameters"]
    hparams.pop("optimizer", None)
    hparams.pop("scheduler", None)
    sd = ckpt["state_dict"]
    model = MatchaTTSInfer(**hparams).to(DEVICE)
    model.load_state_dict(sd, strict=False)
    model.eval()
    print(f"[+] {model_name} loaded!")
    return model


def process_text(text: str, language: str):
    phonemes, phoneme_ids = multilingual_phonemizer(text, language)
    x = torch.tensor(phoneme_ids, dtype=torch.long, device=DEVICE)[None]
    x_lengths = torch.tensor([x.shape[-1]], dtype=torch.long, device=DEVICE)
    print(f"Input text:      <{text}>")
    print(f"Phonetised text: <{phonemes}>")
    return {"x_orig": text, "x": x, "x_lengths": x_lengths, "x_phones": phonemes, "x_phone_ids": phoneme_ids}


def load_vocoder(vocoder_name):
    print(f"[!] Loading {vocoder_name}!")
    if vocoder_name == "vocos":
        vocoder = load_vocos(DEVICE)
    else:
        raise NotImplementedError(f"Vocoder {vocoder_name} not implemented!")
    print(f"[+] {vocoder_name} loaded!")
    return vocoder


@torch.inference_mode()
def pipeline(model, vocoder, text, language, speaker=0, voice_mix=None, n_timesteps=15, length_scale=1.0, debug=False):
    text_processed = process_text(text, language)
    with torch.autocast(device_type="cuda"):
        output = model.synthesise(
            text_processed["x"],
            text_processed["x_lengths"],
            n_timesteps=n_timesteps,
            speaker=speaker,
            voice_mix=voice_mix,
            length_scale=length_scale,
            debug=debug,
        )
    if not debug:
        return trim_trailing_silence(to_waveform(output["mel"], vocoder))
    x_phones = [symbols[id] for id in text_processed["x_phone_ids"]]
    all_durations = output["phoneme_durations"].squeeze(0).tolist()
    all_raw_durations = output["raw_phoneme_durations"].squeeze(0).tolist()
    phoneme_dur_pairs = list(zip(x_phones, all_raw_durations, all_durations))
    waveform = trim_trailing_silence(to_waveform(output["mel"], vocoder))
    encoder_waveform = to_waveform(output["encoder_mel"], vocoder)
    return waveform, encoder_waveform, phoneme_dur_pairs


def to_waveform(mel, vocoder):
    audio = vocoder(mel)
    max_abs = audio.abs().max()
    if max_abs > 1.0:
        audio = audio / max_abs * 0.95
    return audio.cpu().squeeze()


def trim_trailing_silence(audio, silence_threshold_db=-60.0):
    """Trim trailing silence from a 1-D waveform tensor using 10ms RMS windows."""
    window_frames = int(0.01 * SAMPLE_RATE)
    silence_threshold_amp = 10 ** (silence_threshold_db / 20.0)

    n_full_windows = len(audio) // window_frames
    windowed = audio[:n_full_windows * window_frames].reshape(n_full_windows, window_frames)
    rms = windowed.pow(2).mean(dim=1).sqrt()

    trailing_silent_windows = 0
    for i in range(len(rms) - 1, -1, -1):
        if rms[i] < silence_threshold_amp:
            trailing_silent_windows += 1
        else:
            break

    trim_samples = trailing_silent_windows * window_frames
    if trim_samples == 0:
        return audio
    return audio[:-trim_samples]


def convert_to_mp3(waveform):
    start = time.perf_counter()
    audio_np = (waveform.numpy() * 32767).astype(np.int16)
    wav_size = audio_np.size * 2
    mp3_data = encode_mp3(audio_np, sample_rate=SAMPLE_RATE, vbr_quality=5, algorithm_quality=5)
    pct = (len(mp3_data) / wav_size * 100) if wav_size > 0 else 0
    print(f"MP3 conversion: {(time.perf_counter() - start)*1000:.1f}ms | {pct:.0f}% size")
    return mp3_data


def convert_to_opus_ogg(waveform):
    start = time.perf_counter()
    audio_np = (waveform.numpy() * 32767).astype(np.int16).reshape(1, -1)
    wav_size = audio_np.size * 2
    buffer = io.BytesIO()
    container = av.open(buffer, mode='w', format='ogg')
    stream = container.add_stream('libopus', rate=SAMPLE_RATE)
    stream.layout = 'mono'
    stream.bit_rate = 48000
    stream.options = {'compression_level': "5"}
    frame = av.AudioFrame.from_ndarray(audio_np, format='s16', layout='mono')
    frame.sample_rate = SAMPLE_RATE
    for packet in stream.encode(frame):
        container.mux(packet)
    for packet in stream.encode():
        container.mux(packet)
    container.close()
    ogg_data = buffer.getvalue()
    pct = (len(ogg_data) / wav_size * 100) if wav_size > 0 else 0
    print(f"OGG conversion: {(time.perf_counter() - start)*1000:.1f}ms | {pct:.0f}% size")
    return bytes(ogg_data)


