defaults:
  - _self_
  - encoder: default.yaml
  - decoder: default.yaml
  - cfm: default.yaml
  - optimizer: adamw.yaml

_target_: matcha.models.matcha_tts.MatchaTTS
n_vocab: 156

n_spks: ${data.n_spks}

spk_emb_dim: 96

# Shared speaker embedding size for the encoder and duration predictor.
# The decoder has its own spk_emb_dim defined in configs/model/decoder/default.yaml.
n_feats: ${data.n_feats}
data_statistics: ${data.data_statistics}
prior_loss: true
