encoder_params:
  n_feats: ${model.n_feats} # 100, imposed by vocos
  
  # I am training with multiple speakers, so the total number of channels is: (n_channels + spk_emb_dim) = 288
  # (n_channels + spk_emb_dim) / n_heads should be a multiple of 8
  n_channels: 192
  
  # Changed from 768
  # Usually it is 3x or 4x the total number of channels (and a multiple of 8).
  filter_channels: 1152
  
  # Changed from 2, for better prosody. Allows the encoder to produce a much more 
  # accurate prior mu, reducing the "work" the CFM decoder has to do to reach the target mel.
  # It used to be recommended that (n_channels + spk_emb_dim) / n_heads is more than 64, but
  # I think having 6 heads here was beneficial even if it reduced head space to 48
  n_heads: 6 
  
  n_layers: 4
  
  # Increased from 3. It controls receptive field in FFN layers.
  # Each position sees itself + 2 neighbors on each side for better local phonetic context
  kernel_size: 5
  
  # Not a lot of overfitting, no need for a larger value; 
  p_dropout: 0.1
  
  prenet: true

duration_predictor_params:
  filter_channels_dp: 128
  
  # Originally 3; must be an odd number
  kernel_size: 5
  
  # Increase from 0.1 to fight overfitting 
  # DurationPredictor1 with filter_channels_dp: 256, and a dropout of 0.4 still shows more overfitting than diff and prior  
  p_dropout: 0.1
  
  # Increased from 2 
  # Having 4 layers instead of 2 improved the duration estimations dramatically.
  n_layers: 4
