defaults:
  - _self_
  - optimizer: adamw.yaml

_target_: matcha.models.style_encoder.StyleEncoderLightningModule

# Path to a trained Matcha checkpoint
matcha_checkpoint_path: logs/train/v17/checkpoint_epoch=603.ckpt

# Must match the Matcha checkpoint's data config
n_feats: 100
spk_emb_dim: 96

# StyleEncoder architecture
ase_hidden_channels: 256
ase_n_layers: 4
