# @package _global_

defaults:
  - _self_
  - data: corpus-24k
  - model: style_encoder/default
  - callbacks: default
  - logger: tensorboard
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "train_style_encoder"
run_name: style_encoder_v2
tags: ["style_encoder"]

train: True
test: False
limit_val_batches: 0

data:
  num_workers: 2

seed: 1234

# Style encoder path from which to resume training 
ckpt_path: logs/train_style_encoder/style_encoder_v2/runs/2026-05-24_10-28-30/checkpoints/checkpoint_epoch=144.ckpt

model:
  optimizer:
    # reduced from 1e-4 to 5e-5 at epoch 200
    lr: 1e-4